# IPython log file


WellData.WellData('A11', startdate='today', qo=arange(6)).plot('ql')
import WellData
WellData.WellData('A11', startdate='today', qo=arange(6)).plot('ql')
reload(WellData)
WellData.WellData('A11', startdate='today', qo=arange(6)).plot('ql')
get_ipython().magic(u'pdb')
WellData.WellData('A11', startdate='today', qo=arange(6)).plot('ql')
reload(WellData)
WellData.WellData('A11', startdate='today', qo=arange(6)).plot('ql')
reload(WellData)
WellData.WellData('A11', startdate='today', qo=arange(6)).plot('ql')
WellData.WellData('A11', startdate='today', qo=arange(1,6)).plot('ql')
close('all')
WellData.WellData('A11', startdate='today', qo=arange(1,6)).plot('ql')
random
get_ipython().magic(u'pinfo random')
get_ipython().magic(u'pinfo rand')
rand(100)
WellData.WellData('A11', startdate='today', qo=1000*rand(500)).plot('ql')
WellData.WellData('A11', startdate='today', qo=1000*rand(500)).plot('ql', 'p)
WellData.WellData('A11', startdate='today', qo=1000*rand(500)).plot('ql', 'o')
WellData.WellData('A11', startdate='today', qo=1000*rand(500)).plot('ql', fmt='o')
WellData.WellData('A11', startdate='today', qo=1000*rand(500)).plot('ql', fmt='o-')
WellData.WellData('A11', startdate='today', qo=1000*rand(500)).plot('ql', fmt='o--')
WellData.WellData('A11', startdate='today', qo=800+200*rand(500)).plot('ql', fmt='o-')
WellData.WellData('A11', startdate='today', qo=800+200*rand(500)).plot('ql')
ylim(0,1000)
ylim(0,1100)
get_ipython().magic(u'run -i WellData.py')
get_ipython().magic(u'run -i WellData.py')
get_ipython().magic(u'run -i WellData.py')
get_ipython().magic(u'run -i WellData.py')
close('all')
get_ipython().magic(u'run -i WellData.py')
